### ISSUE TITLE
Consider replacing github.com/shurcooL/graphql with something easier to use

### ISSUE THREAD

**Issue by yob** [buildkite/terraform-provider-buildkite#113]
In #112 I wrestled a lot with this library. It was **much** harder to get it generating the query shape I wanted than I hoped.

Maybe I was just using it wrong, but I reckon it's worth considering swapping it out for something else.

https://github.com/buildkite/cli has a super minimal custom thing (see https://github.com/buildkite/cli/blob/master/graphql/client.go) that would be much easier to use, maybe we could borrow that, or extract it to our own mini graphql module? That particular package is 3 years old too, so maybe there's another modern and easy to use third party graphql client to consider.

Some things to consider:

* Maybe we just want to build the query as a string, rather than use deep reflection and struct tags. Less magic, and easier to get the query shape we want? This is what we do in https://github.com/buildkite/cli
* Some way to enable HTTP debugging and have the raw graqphql request and repsonse printed to the screen would be **super8* useful. In ended up forking github.com/shurcooL/graphql into github.com/yob/graphql and adding this for local debugging

**Comment by yob** [comment]
While doing this, it would also be worth trying to wrap the graphql up into an module-internal API client of some kind. We have raw graphql scattered all over the resource implementations, and it'd be so much nicer if they could instead  call a set of facade functions that hide graphql under the hood (`createPipeline`, `getPipelineById()`, `deletePipeline()`, `createAgentToken()`, etc)

**Comment by yob** [comment]
Aother option is github.com/machinebox/graphql, which is used in the tink-ab community terraform provider: https://github.com/tink-ab/terraform-provider-buildkite/blob/07892a53aec39367af257c7f2f404ff2d0cf2ae2/buildkite/client/team_pipeline.go

**Comment by yob** [comment]
oh, it looks a bit abandoned :cry:

**Comment by jradtilbrook** [comment]
I'm not completely sure why I didn't use [go-buildkite](https://github.com/buildkite/go-buildkite) when I first started this plugin but perhaps that would be a better approach - to improve that SDK and make use of it here rather than raw API requests

**Comment by jradtilbrook** [comment]
I've seen a few instances where people are just using a raw HTTP POST request and a string for the query/mutation. It's very clear whats going on in that case and might honestly be better than trying to use a smart library.

Each time I have to mess with this GraphQL library I struggle and it takes a long time.

**Comment by mcncl** [comment]
Closed as we are slowly migrating to genqlient
