### ISSUE TITLE
Support specifying pipeline team membership using team id

### ISSUE THREAD

**Issue by yob** [buildkite/terraform-provider-buildkite#117]
Currently we support placing pipelines in a team like this:

```hcl
resource "buildkite_pipeline" "repo2" {
    name = "repo2"
    repository = "git@github.com:org/repo2"
    steps = file("./steps.yml")

    team {
        slug = "everyone"
        access_level = "READ_ONLY"
    }
}
```

Specifying the team via a slug is nice and readable, but it requires an API call to map it to a team graphql ID. We'd like to deprecate the slug, and instead recommend this approach:

```hcl
resource "buildkite_team" "everyone" {
    name = "everyone"
}

resource "buildkite_pipeline" "repo2" {
    name = "repo2"
    repository = "git@github.com:org/repo2"
    steps = file("./steps.yml")

    team {
        id = buildkite_team.everyone.id
        access_level = "READ_ONLY"
    }
}
```

Adding a data source for buildkite_team would be a nice bonus too. We'd need to continue supporting slug for backwards compatibility, but it could be deprecated.

**Comment by keith** [comment]
I hit this but the frustrating part was it seems the error is quite poor, when I try to apply I just see:

```
buildkite_pipeline.iosstaging: Creating...

Error: No ID was supplied
```

**Comment by vgrigoruk** [comment]
> Adding a data source for buildkite_team would be a nice bonus too. We'd need to continue supporting slug for backwards compatibility, but it could be deprecated

Alternatively, you can just make a breaking change and release a new major version of the provider...

**Comment by yob** [comment]
> Error: No ID was supplied

rats, that's really not a very useful error :thinking: 

It's not even useful as a pointer to where in the coed it might be coming from. `No ID was supplied` isn't in this code base, so I'm assuming it might be generated server side and included in a graphql response. Did it occur when the slug was empty or not-valid? Maybe:

```hcl
resource "buildkite_pipeline" "repo2" {
    name = "repo2"
    repository = "git@github.com:org/repo2"
    steps = file("./steps.yml")

    team {
        slug = ""
        access_level = "READ_ONLY"
    }
}
```

> And it doesn't look like ID is shown in the docs https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/team

Oops, thanks for picking this up. I've opened a PR to fix the docs.

> And this example shows using the slug directly https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/pipeline#example-usage

Do you think that example would be better if it pulled the team slug from a `team` resource? I think maybe the docs were trying to keep to simple cases were possible, and avoid mixing in additional resources. It doesn't necessarily need to stay that way though :thinking:

**Comment by keith** [comment]
So I discovered later it was because the team `slug` was just invalid, I was using the team's name `Client Tooling` assuming that would work when the slug was actually `client-tooling`

**Comment by jradtilbrook** [comment]
We are moving away from the usage of blocks within resources as that is the [recommended approach](https://developer.hashicorp.com/terraform/plugin/framework/handling-data/blocks) for terraform provider developers. Many other providers use a separate resource for this sort of thing.

We'll continue to support this team block (using team slug) for some time - notice will be given when it gets removed.

It will be deprecated upon the implementation of a new resource which will look something like:
```hcl
resource "buildkite_pipeline_team" "team_a" {
  pipeline_id = ""
  team_id = ""
  access_level = ""
}
```

I'll close this ticket out now
