### ISSUE TITLE
Is it possible to create Github webhooks via terraform?

### ISSUE THREAD

**Issue by chrisnankervis** [buildkite/terraform-provider-buildkite#133]
We're now managing our Buildkite pipelines via your terraform provider - thank you! We haven't had much luck configuring Github webhooks via the provider though (it doesn't look like it's even supported). We're manually creating the webhooks via the Buildkite UI once the pipeline has been created via terraform for now. Is this the expected approach and are there any plans to change the way this works in the future?

**Comment by chrisnankervis** [comment]
This may already be [in the works](https://github.com/buildkite/terraform-provider-buildkite/tree/create-pipeline-auto-create-webhook) 🤔

**Comment by yob** [comment]
Oh, I'd forgotten about @JuanitoFatas's spike! Thanks for the reminder :)

The graphql API does support auto-creating webhooks on GitHub and in theory we could support it in the terraform provider. We're not opposed to the idea, but it might also feel a bit awkward. That mutation asks buildkite to change state on github, and the github state isn't returned in the graphql response. That would make it difficult to ensure terraform reflects the correct state. 

Are you open to using the github provider in tandem with this provider? One option that would work quite reliably (including restoring webhooks if they were deleted on github) might look like this:

```hcl
resource "github_repository" "app" {
	name         = "app"
	description  = "My Great App"
	homepage_url = "http://example.com"
}

resource "github_repository_webhook" "app-buildkite" {
	repository = github_repository.app.name
	events     = ["push", "pull_request"]
	configuration {
		url          = buildkite_pipeline.app.webhook_url
		content_type = "json"
	}
}

resource "buildkite_pipeline" "app" {
        name = "My Great App"
        repository = github_repository.app.ssh_clone_url
}
```

Alternatively, if your github and buildkite config live in separate terraform projects, a version of the above in the github project should work with `resource "buildkite_pipeline" "app" {` changed to `data "buildkite_pipeline" "app" {
`

**Comment by chrisnankervis** [comment]
Thanks for taking the time to get back to us @yob. We had an inkling that this might be the case after a few internal discussions. I tend to agree that having the Buildkite Terraform provider change GitHub state doesn't feel quite right.

I don't believe we currently have any Terraform configuration for GitHub but if we were to do so it would live in a separate repository. Using the solution that you proposed or using Terraform modules for the `github_repository` and `github_repository_webhook` resources in our Buildkite Terraform should do the trick. We could even bake the all of the resources needed into one `pipeline` module so that you get the GitHub webhooks out of the box.

As far as I'm concerned this issue is resolved, thanks again!
