### ISSUE TITLE
[Feature request] Team members

### ISSUE THREAD

**Issue by bluemalkin** [buildkite/terraform-provider-buildkite#137]
It would be great to expand the `buildkite_team` resource and have something like `buildkite_team_member`

```
resource "buildkite_team_member" "my_team_member" {
  team_id  = buildkite_team.team.id
  username = "SomeUser"
  role     = "MEMBER"
}
```

**Comment by mogggggg** [comment]
Just adding on to this (please let me know if you'd prefer a separate feature request) - it'd be great if there were data sources available for `buildkite_team`. We're transitioning all our pipelines to be managed with Terraform and being able to use existing teams we've already setup via the UI would be awesome.

**Comment by yob** [comment]
@bluemalkin we agree, we're keen on making it possible to manage team membership via terraform, probably via a distinct resource as you've suggested.

@mogggggg I reckon a dedicated GH issue would help keep your proposal visible. It's uncontroversial and a good idea - and it could be shipped with out without a resource for managing team membership.

**Comment by jradtilbrook** [comment]
Just to link things up. @mogggggg created ticket #139 to cover the `buildkite_team` data source
