### ISSUE TITLE
Add a data source for buildkite_team

### ISSUE THREAD

**Issue by mogggggg** [buildkite/terraform-provider-buildkite#139]
It would be really handy to have a `buildkite_team` data source to manage teams that were created in the UI. I think it will make it easier for people to migrate to using the Terraform provider as they can re-use what's already been created.

**Comment by vgrigoruk** [comment]
as an alternative, you may consider importing existing teams into Terraform. With a little bit of scripting, it is super easy to generate necessary terraform configs and import existing teams into terraform state in no time :) Just use the output of GraphQL API and pipe it to this script.

**Comment by yob** [comment]
@mogggggg we're very open to having a team data source, but we're also pretty busy at the moment. Are you up for opening a PR?

#106 would be a good model, where we added a data source version of the existing pipeline resource. I reckon a teams version might be under 100 lines of go, plus acceptance tests. We'd be happy to setup a free buildkite org for running the tests against as well.

**Comment by mogggggg** [comment]
@yob No worries, totally understand!

I can try to make some time to look into it, but I'm not very familiar with Go so it might take me a while

**Comment by thekyz** [comment]
@jradtilbrook could I take a stab at implementing this? I don't see anybody working on that feature and that would definitely simplify a lot of things for us

**Comment by pzeballos** [comment]
Hey @thekyz! Sure! 🙏 we'll be happy to review it!
