### ISSUE TITLE
Bug in importing schedules

### ISSUE THREAD

**Issue by thomasvdpol** [buildkite/terraform-provider-buildkite#140]
We've been expanding our TF setup to include additional resources and found ourselves needing to import state of existing schedules. They were created using this Buildkite provider so they should all be set up right, but all of them throw this error:

```
module.managed-repository-for-something.buildkite_pipeline_schedule.buildkite_pipeline_schedule: Importing from ID "org/slug/relevant_id"...

Error: nil entry in ImportState results. This is always a bug with
the resource that is being imported. Please report this as
a bug to Terraform.
```

We've got an easy workaround in that we can just delete and re-create the schedules without any real downsides, but I figured I'd flag it here at least.

**Comment by yob** [comment]
Thanks for capturing the issue, it definitely seems like something we want to fix :thinking:

**Comment by yob** [comment]
I just tried to reproduce this and in my test it works fine. I help write the code, so presuambly I'm making an assumption in how to hold and use it. Maybe you can spot the difference?

I used this terraform:

```hcl
provider "buildkite" {
}

resource "buildkite_pipeline" "test" {
  name       = "Test 1"
  repository = "https://github.com/buildkite/terraform-provider-buildkite.git"

  steps = ""
}

resource "buildkite_pipeline_schedule" "foo" {
  pipeline_id = buildkite_pipeline.test.id
  label       = "foo"
  branch      = "master"
  cronline    = "* * * * 1"

}
```
.. and imported the schedule like this:

```
BUILDKITE_API_TOKEN=xxx BUILDKITE_ORGANIZATION=yob-opensource terraform import buildkite_pipeline_schedule.foo "yob-opensource/test-1/47cb5a9f-e6ce-44cf-89db-393e36d0cc46"
```

The UUID in the import statement came from the URL of the schedule page: https://buildkite.com/yob-opensource/test-1/settings/schedules/47cb5a9f-e6ce-44cf-89db-393e36d0cc46

Can you see any differences to the process you used?

**Comment by thomasvdpol** [comment]
The main difference I can see is I'm using the GraphQL output to generate import statements, so I've got what looks like a base64 encoded string as the id. This works fine for importing the pipeline state, which is how I got there.

The UUID is also accessible in the GraphQL so once I grabbed that instead and amended my import statements, things came together and worked just fine!

So this seems more a case of a slightly confusing error message and operator error. Apologies!

**Comment by yob** [comment]
> The main difference I can see is I'm using the GraphQL output to generate import statements, so I've got what looks like a base64 encoded string as the id. This works fine for importing the pipeline state, which is how I got there.

Oh, right.

It seems we're inconsistent across resources with whether we import via graphql ID (the base64 encoded ones) or UUID. Awkward.

It'd be nice to standardise (see #143), but at the very least I think we should return a nicer error when importing a pipeline schedule and the provided ID doesn't match anything.
