### ISSUE TITLE
Handle repository renames

### ISSUE THREAD

**Issue by thomasvdpol** [buildkite/terraform-provider-buildkite#147]
As our previously Buildkite-only repository now manages GitHub repositories as well, I decided to rename it using the GH repo's module definition:

```
Error: Provider produced inconsistent final plan
--
  |  
  | When expanding the plan for
  | module.managed-repository-infra-buildkite.buildkite_pipeline.buildkite_pipeline[0]
  | to include new values learned so far during apply, provider
  | "registry.terraform.io/buildkite/buildkite" produced an invalid new value for
  | .repository: was
  | cty.StringVal("git@github.com:greensync/infra-buildkite.git"), but now
  | cty.StringVal("git@github.com:greensync/infra-repositories.git").
  |  
  | This is a bug in the provider, which should be reported in the provider's own
  | issue tracker.

```

The modules look more or less like you'd expect:

```terraform
resource "github_repository" "github_repository" {
  name          = var.repo_name
  description   = var.repo_desc
  ...
}

resource "buildkite_pipeline" "buildkite_pipeline" {
  count      = var.build_pipeline ? 1 : 0
  name       = github_repository.github_repository.name
  repository = github_repository.github_repository.ssh_clone_url
   ...
}
```

There's also the Webhook creation and schedule but I don't think they relate to this.

We fixed it in the GUI but I figured this was a rare enough edge case you might want to see it.

**Comment by yob** [comment]
> This is a bug in the provider, which should be reported in the provider's own issue tracker

Seems like something we should fix I guess!

Why does it consider the new string value to be invalid though? :thinking:

**Comment by thomasvdpol** [comment]
> Why does it consider the new string value to be invalid though? 🤔

I have to admit I'm truly at a loss there. That's mainly why I didn't change the output at all, the repo names aren't particularly sensitive and they're the exact values it was having issues with. We changed the value through the GUI and everything was fine.

**Comment by jradtilbrook** [comment]
Hi @thomasvdpol, can you confirm a few things for me so we can figure out this problem? (Hopefully it's not too late to find this information out)

1. What version of terraform?
2. What version of this plugin?
3. What properties on the `buildkite_pipeline` resource did you change? Just the name and repository to reference the `github_repository` resource dynamically?
4. Did you perform this change in one `terraform apply`? ie - create/rename GitHub repo _and_ add the dynamic reference to `buildkite_pipeline`? (I wonder if there is an issue doing it at the same time for terraform to figure out dependency ordering and if you did it across 2 `apply`s is might be okay)
5.

**Comment by thomasvdpol** [comment]
Hey, it's been a while since this happened so I can't get to exact details, sorry!
> 1. What version of terraform?

I think it'd have been 0.12 at the time. We're on 1.x now so hard to go back and check.

> 2. What version of this plugin?

Whichever was the current version at time of writing. Sorry, I don't have specifics here either.

> 3. What properties on the `buildkite_pipeline` resource did you change? Just the name and repository to reference the `github_repository` resource dynamically?

Same again - though I suspect the change was very small, likely only the name of the repository.

> 4. Did you perform this change in one `terraform apply`? ie - create/rename GitHub repo _and_ add the dynamic reference to `buildkite_pipeline`? (I wonder if there is an issue doing it at the same time for terraform to figure out dependency ordering and if you did it across 2 `apply`s is might be okay)

I suspect I did exactly this, yes. It could have been ok in two applies. I ended up going through the GUI to make it all match the state, as I said, and haven't had the occasion to rename a GitHub repo since.

**Comment by jradtilbrook** [comment]
This is quite old now. We've done a few changes around pipeline resource and given its such a rare case we are opting to close this without looking into a fix. If it comes up again please open a new issue and we can have another look
