### ISSUE TITLE
Filter builds using a conditional filter support

### ISSUE THREAD

**Issue by gu-kevin** [buildkite/terraform-provider-buildkite#149]
In the Github setting for pipelines, there is a checkbox field **Filter builds using a conditional** with a input box for conditional expression that is not exposed in the Terraform provider.

![Screenshot 2021-05-14 4 49 16 PM](https://user-images.githubusercontent.com/52257064/118342769-bacf9000-b4d9-11eb-88ca-56bf431f88e2.png)

**Comment by yob** [comment]
We'd love this option to be supported in the terraform provider.

It's currently feature flagged and gradually rolling out to more customers - once it's officially out (and documented) we're keen to include it.

**Comment by gu-kevin** [comment]
Is there a timeline when can expect this feature to rolled out?

**Comment by yob** [comment]
The good news is this feature is now generally available and documented: https://buildkite.com/docs/pipelines/conditionals#conditionals-in-pipelines

There are [two new properties available in the REST API](https://buildkite.com/docs/apis/rest-api/pipelines#provider-settings-properties): `filter_enabled` and `filter_condition`.

They could be added to the TF provider here: https://github.com/buildkite/terraform-provider-buildkite/blob/882116ff531c022a51e46f22a4f7313e777ad162/buildkite/resource_pipeline.go#L145-L242

.. and set/received via the API using this struct: https://github.com/buildkite/terraform-provider-buildkite/blob/882116ff531c022a51e46f22a4f7313e777ad162/buildkite/resource_pipeline.go#L425-L447

If you're up for opening a PR, one of us can review and release a new version :heart:

**Comment by yob** [comment]
Shipped in v0.5.0 :tada:
