### ISSUE TITLE
Add resource for Notification Services (eg. webhooks, eventbridge, slack)

### ISSUE THREAD

**Issue by keith** [buildkite/terraform-provider-buildkite#154]
It would be great if you could manage webhooks via terraform, specifically because the permissions required to edit them are so sensitive

**Comment by yob** [comment]
Would this be a terraform resource that calls our API that installs webhooks into the GitHub repo? if so there's some existing discussion in #133  that might be interesting, and we could re-open that issue?

**Comment by keith** [comment]
Sorry I should have been more clear that in this case I meant the global "notification services" webhooks

**Comment by plenti-chris-fowles** [comment]
adding my use case here - we're looking to ifra as code up some data ingestion pipelines of which setting up eventbus for notifications is part of. would be great to be able to manage this via terraform

**Comment by tovbinm** [comment]
+1!!

**Comment by TerrorJacktyl** [comment]
+1 for this please

My use case is wishing to add a notification service for a bunch of slack channels. It's tiresome having to ask a Buildkite admin to add a new service for every channel.

**Comment by jradtilbrook** [comment]
Hi folks, thanks for registering your interest. We'd love to get this into terraform but it is not in the roadmap for quite a while unfortunately. We hope to get to this next year

**Comment by mcncl** [comment]
I'm going to close this issue; the work to support it isn't planned and so leaving it open implies it's something we can scope in.

Once notification services are supported in GraphQL or REST then we'll be able to action this work, but for now there are no plans to tackle this in the next 6-12 months.
