### ISSUE TITLE
Incorrect import of BK pipeline TF states (provider_settings)

### ISSUE THREAD

**Issue by sentinel1985** [buildkite/terraform-provider-buildkite#162]
We have noticed that the TF Buildkite provider does not (always) import the TF state of a pipeline correctly - causing `terraform apply` to apply unwanted changes. 

Specifically, the Github option `build_branches` (see: [BK TF provider documentation](https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/pipeline#build_branches)) is sometimes read as `false` by the BK TF provider, although it is enabled in the BK console.

<img width="368" alt="Screen Shot 2021-08-09 at 1 40 52 pm" src="https://user-images.githubusercontent.com/10666613/128658145-68be18ce-ae1b-4c14-8f93-f69cd5365261.png">

We could trace back this issue to an error (?) of the BK API, which reports sometimes no value at all and sometimes `true` (correct!) for `build_branches` configs of different BK pipelines.

_Wrong case:_
```
curl -s 'https://api.buildkite.com/v2/organizations/<organization-slug>/pipelines/<pipeline1-slug>' -H 'authorization: Bearer <token>' | jq ".provider.settings.build_branches"

null
```

_Correct case:_
```
curl -s 'https://api.buildkite.com/v2/organizations/<organization-slug>/pipelines/<pipeline2-slug>' -H 'authorization: Bearer <token>' | jq ".provider.settings.build_branches"

true
```

As it seems, the BK TF provider interprets no value (`null`) mistakenly as `false`.

_Hint:_
It could be the case that this issue is not limited to the `build_branches` configuration, only.

**Comment by jradtilbrook** [comment]
Thanks for reporting this 👍 

We are approaching a v1.0 release and have done major refactors to the provider_settings part of the provider. I don't believe this is a relevant bug any more. If in fact this comes up again after the v1.0 release, please reopen it
