### ISSUE TITLE
Terrform apply crashes when creating buildkite_team

### ISSUE THREAD

**Issue by blockoneheera** [buildkite/terraform-provider-buildkite#167]
I just started exploring terraform for buildkite to create team members and assign users to it, but looks like when I try and apply code it crashes with below error.

I have tried using TF version 0.13.5 and latest too: v1.0.9 but it crashes in both the cases

Provider I am using
```
-----------------------------------------------------------------------------------------------------------
terraform {
  required_providers {
    buildkite = {
      source = "buildkite/buildkite"
      version = "0.5.0"
    }
  }
}

provider "buildkite" {
    api_token = "<token>" # can also be set from env: BUILDKITE_API_TOKEN
    organization = "B1x" # can also be set from env: BUILDKITE_ORGANIZATION
}
-----------------------------------------------------------------------------------------------------------
```

Plan looks good though. plan:
```
-----------------------------------------------------------------------------------------------------------
  # buildkite_team.non_prod_deployers will be created
  + resource "buildkite_team" "non_prod_deployers" {
      + default_member_role = "MEMBER"
      + default_team        = true
      + description         = "creating_via_TF"
      + id                  = (known after apply)
      + name                = "Non_Prod_Deployers"
      + privacy             = "VISIBLE"
      + slug                = (known after apply)
      + uuid                = (known after apply)
    }
-----------------------------------------------------------------------------------------------------------
```

error:
```
-----------------------------------------------------------------------------------------------------------
buildkite_team.non_prod_deployers: Creating...
╷
│ Error: Plugin did not respond
│ 
│   with buildkite_team.non_prod_deployers,
│   on main.tf line 1, in resource "buildkite_team" "non_prod_deployers":
│    1: resource "buildkite_team" "non_prod_deployers" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin
│ logs may contain more details.
╵
```
Stack trace from the terraform-provider-buildkite_v0.5.0 plugin:

```
panic: interface conversion: graphql.ID is nil, not string

goroutine 70 [running]:
github.com/buildkite/terraform-provider-buildkite/buildkite.GetOrganizationID(0xc00051e079, 0x3, 0xc0005102d0, 0x0, 0xc000536f10, 0x1820208, 0xc0005656f8)
        github.com/buildkite/terraform-provider-buildkite/buildkite/util.go:27 +0x1bf
github.com/buildkite/terraform-provider-buildkite/buildkite.CreateTeam(0x18d1128, 0xc000536f00, 0xc000197d80, 0x170b6a0, 0xc00053a220, 0xc00057acb0, 0x1412dea, 0xc00053a8e0)
        github.com/buildkite/terraform-provider-buildkite/buildkite/resource_team.go:101 +0x6f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0xc0000a88f0, 0x18d10b8, 0xc000554e00, 0xc000197d80, 0x170b6a0, 0xc00053a220, 0x0, 0x0, 0x0)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/helper/schema/resource.go:276 +0x1ed
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0000a88f0, 0x18d10b8, 0xc000554e00, 0xc00054f180, 0xc00053a8e0, 0x170b6a0, 0xc00053a220, 0x0, 0x0, 0x0, ...)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/helper/schema/resource.go:387 +0x674
github.com/hashicorp/terraform-plugin-sdk/v2/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc00000c0f0, 0x18d10b8, 0xc000554e00, 0xc00054ef50, 0xc00000c0f0, 0xc00000c100, 0x1820208)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/internal/helper/plugin/grpc_provider.go:952 +0x8ef
github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler.func1(0x18d10b8, 0xc000554e00, 0x17b6600, 0xc00054ef50, 0xc000554e00, 0x17411a0, 0xc000574601, 0xc000511170)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/internal/tfplugin5/tfplugin5.pb.go:3312 +0x89
github.com/hashicorp/terraform-plugin-sdk/v2/plugin.Serve.func3.1(0x18d1160, 0xc000574690, 0x17b6600, 0xc00054ef50, 0xc00053a780, 0xc000511170, 0xc0005b7ba0, 0x10a3e26, 0x1790360, 0xc000574690)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/plugin/serve.go:76 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x17c3e00, 0xc00000c0f0, 0x18d1160, 0xc000574690, 0xc000536a20, 0xc000304060, 0x18d1160, 0xc000574690, 0xc000556180, 0x17c)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.0.3/internal/tfplugin5/tfplugin5.pb.go:3314 +0x150
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000e0540, 0x18d7a98, 0xc000103380, 0xc000538200, 0xc0000a0d20, 0x1cade40, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1171 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc0000e0540, 0x18d7a98, 0xc000103380, 0xc000538200, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1494 +0xccf
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc00012e3e0, 0xc0000e0540, 0x18d7a98, 0xc000103380, 0xc000538200)
        google.golang.org/grpc@v1.30.0/server.go:834 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.30.0/server.go:832 +0x1fd

Error: The terraform-provider-buildkite_v0.5.0 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
-----------------------------------------------------------------------------------------------------------
```
Refering: https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/team#default_team

**Comment by jradtilbrook** [comment]
Hi @blockoneheera thanks for reaching out. I believe the issue is that the organisation slug you are using is incorrect. It should be `b1x` (all lowercase).

The provider should certainly not crash in this case but hopefully that can get you on your way. I'll create another issue to improve the error messaging and handling for this

**Comment by blockoneheera** [comment]
Thanks, you are right, I was using an uppercase letter. Sorry for the
confusion.

Regards
Heera

On Tue, Nov 2, 2021 at 12:28 PM Jarryd Tilbrook ***@***.***>
wrote:

> ------------------------------
> *[External Email: Use caution with links and attachments]*
> ------------------------------
>
> Hi @blockoneheera
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_blockoneheera&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=11LCe0iE94V6m42Fifo43eYxbhxC_pSVTkNigmnAwyg&m=IzZjHAEU5fCB4TWxyE1GIlq03XrsaPM3oK0W-fuYD2B9o3wbBifcoCfSVWSgsvtC&s=O4_IM8g9GXumwp7ZXyVF2eGRw6zJDvF07ldyDOB8-7k&e=>
> thanks for reaching out. I believe the issue is that the organisation slug
> you are using is incorrect. It should be b1x (all lowercase).
>
> The provider should certainly not crash in this case but hopefully that
> can get you on your way. I'll create another issue to improve the error
> messaging and handling for this
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_buildkite_terraform-2Dprovider-2Dbuildkite_issues_167-23issuecomment-2D957093229&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=11LCe0iE94V6m42Fifo43eYxbhxC_pSVTkNigmnAwyg&m=IzZjHAEU5fCB4TWxyE1GIlq03XrsaPM3oK0W-fuYD2B9o3wbBifcoCfSVWSgsvtC&s=gKwh6t5HdmP6Qz_SfDxSwT94KChHKaWv1_0A7nUB_b4&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AVQG2EA6GKBS6LEB35JU3ALUJ5SG3ANCNFSM5GZPWTSQ&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=11LCe0iE94V6m42Fifo43eYxbhxC_pSVTkNigmnAwyg&m=IzZjHAEU5fCB4TWxyE1GIlq03XrsaPM3oK0W-fuYD2B9o3wbBifcoCfSVWSgsvtC&s=cl1-XztOy7kFDVSn-xf5Ex1cS0ju4CU2ypmwfLQbjbI&e=>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=11LCe0iE94V6m42Fifo43eYxbhxC_pSVTkNigmnAwyg&m=IzZjHAEU5fCB4TWxyE1GIlq03XrsaPM3oK0W-fuYD2B9o3wbBifcoCfSVWSgsvtC&s=yeZ9BKl89k01sTJfC97e3ijcWi--2eqL2Vm8zJtXOwE&e=>
> or Android
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=sSVGO1PAPMGyxGLZsRfH-A&r=11LCe0iE94V6m42Fifo43eYxbhxC_pSVTkNigmnAwyg&m=IzZjHAEU5fCB4TWxyE1GIlq03XrsaPM3oK0W-fuYD2B9o3wbBifcoCfSVWSgsvtC&s=dIz-z0xtKYc5Llog1f2OlGp3J2FO8XAuYxKgT9lK3Fo&e=>.
>
>


-- 

Heera Singh
Senior Engineer, DevOps, SGP, Exchange Infrastructure
***@***.***
www.bullish.com
The information contained in this email is confidential together with any
information contained in any attachments to this email. You should not
disclose, give or copy the information to anyone other than the person(s)
who are named or referenced above. The law may also protect the information
as a legally privileged document and/or as a copyright work. If you have
received this email and you are not the person named or referenced above,
please let the sender know and delete the email from your computer (and, if
applicable, your computer system(s) and server(s)). Investment in crypto
assets involves risks. Please refer to our warning statement in relation to
any related marketing materials or communications here
<https://bullish.com/privacy-notice/>.
