### ISSUE TITLE
Improve error messages and handling

### ISSUE THREAD

**Issue by jradtilbrook** [buildkite/terraform-provider-buildkite#169]
This plugin will sometimes just crash when something "not ideal" happens which is a bad experience. We should improve the handling to print better messages and try to exit as gracefully as possible.

eg. see #167 (there are possibly other issues as well to check for)

**Comment by mcncl** [comment]
@jradtilbrook I'm closing this issue as it's stale and there are likely future examples we'll see that can provide more context than this issue. As it stands, this issue would require a lot of digging and some forcing of failures to recreate.
