### ISSUE TITLE
[Feature request] Support cluster in buildkite_pipeline resource

### ISSUE THREAD

**Issue by kate-syberspace** [buildkite/terraform-provider-buildkite#179]
The graphql `pipelineCreate` mutation already accepts `cluster`. 

It would be handy to support this in the `buildkite_pipeline` terraform resource as well.

**Comment by jradtilbrook** [comment]
This is something we will definitely be adding to the provider in the future. However, we don't have a timeline on this feature at the moment.

If you are willing to have a go at it and submit a PR we would be more than happy to review and work with you on it

**Comment by kate-syberspace** [comment]
Thanks @jradtilbrook , I've opened a [PR](https://github.com/buildkite/terraform-provider-buildkite/pull/181).
