### ISSUE TITLE
buildkite_pipeline.branch_configuration won't update to empty string

### ISSUE THREAD

**Issue by brianseeders** [buildkite/terraform-provider-buildkite#184]
Consider this resource:

```hcl
resource "buildkite_pipeline" "daily" {
  name        = "kibana / daily"
  description = "Runs full CI daily and on merge"
  repository  = "https://github.com/elastic/kibana.git"
  steps       = <<-EOT
  steps:
    - label: ":pipeline: Pipeline upload"
      command: buildkite-agent pipeline upload .buildkite/pipelines/hourly.yml
  EOT

  default_branch       = ""
  branch_configuration = "main"

  provider_settings {
    build_branches      = true
    build_tags          = false
    build_pull_requests = false

    trigger_mode = "code"
  }
}
```

If `branch_configuration` is updated to `""`, terraform will not actually update the pipeline (it doesn't even show up in the plan). A different, non-empty string works fine.

**Comment by jradtilbrook** [comment]
Thanks for raising this @brianseeders 👍 

I had a quick look at the state of the GraphQL API and it looks like this comment is now wrong so we can hopefully quite easily fix this. Please feel free to open a PR for the fix if you are able to
https://github.com/buildkite/terraform-provider-buildkite/blob/main/buildkite/resource_pipeline.go#L433
