### ISSUE TITLE
M1 Mac Support 

### ISSUE THREAD

**Issue by mhornbacher** [buildkite/terraform-provider-buildkite#185]
GoReleaser supports darwin_arm64 and version 0.5.0 had this support

**Comment by mhornbacher** [comment]
Cloning and running `goreleaser build` locally works just fine on 0.6.0. Perhaps the artifact did not upload?

**Comment by jk-kp** [comment]
This is an issue for us too, would be great to have this resolved, though `0.5.0` is fine for us for now.

**Comment by jradtilbrook** [comment]
Ahh yes good hinting @mhornbacher! It seems we will need to update some stuff to get this working again.
![Screen Shot 2022-03-21 at 20 31 36](https://user-images.githubusercontent.com/6128798/159261620-7210c1c8-2dcc-48b2-858d-6a7dd15d258a.png)

I think we'll need to upgrade GoReleaser according to https://goreleaser.com/deprecations/#builds-for-darwinarm64.

It might be a little hard to test exactly this script locally for you, but you could probably manually test it out against GoReleaser to reproduce this issue and then confirm upgrading fixes it and provide us PR if you're up for it. The line/file you are looking for should be https://github.com/buildkite/terraform-provider-buildkite/blob/da1f22856c3943620f6cd5bc404624e42b16a1a7/.buildkite/steps/release.sh#L48

**Comment by mhornbacher** [comment]
@jradtilbrook I updated the download and tested a `goreleaser build` in `docker-compose` just as it is run in CD and it generated the binary just fine :)
