### ISSUE TITLE
Add support for allow_rebuilds resource

### ISSUE THREAD

**Issue by chanukov** [buildkite/terraform-provider-buildkite#187]
In Buildkite UI  under pipeline Settings --> Builds there is a button called Allow Rebuilds

```
Rebuilds
Allow Rebuilds

Uncheck this option to disable rebuilds entirely.
```

It currently cannot be set in terraform, while all other  variables can be found in https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/pipeline

Ideally just like we can set cancel_intermediate_builds = false/true
we should be able to set 
allow_rebuilds = false/true

**Comment by jradtilbrook** [comment]
Hi @chanukov that makes sense. Are you open to contributing this improvement?

**Comment by jradtilbrook** [comment]
@chanukov I've merged this feature now and will be releasing a new version of the provider shortly

**Comment by chanukov** [comment]
Thanks for working on this. Exited to take this in.
