### ISSUE TITLE
Invalid states

### ISSUE THREAD

**Issue by keith** [buildkite/terraform-provider-buildkite#194]
I noticed when managing pipelines via terraform you can get yourself into invalid states that buildkite doesn't actually support. I think it would be ideal if it would error in this case instead. For example:

```
  provider_settings {
    trigger_mode = "none"
    build_branches = false
    build_pull_requests = false
    publish_commit_status = true
    cancel_deleted_branch_builds = true
  }
```

Using `publish_commit_status` and `cancel_deleted_branch_builds` here seems to be invalid when `trigger_mode = "none"`. You can pretty much see this in the UI because those checkboxes aren't exposed in this case:

<img width="786" alt="image" src="https://user-images.githubusercontent.com/283886/164513064-95e1e7f9-3210-4939-a920-cd72b05038bf.png">

And when you change the trigger mode in the UI you can see the checkboxes are set correctly, just likely ignored:

<img width="455" alt="image" src="https://user-images.githubusercontent.com/283886/164513148-d7817121-006d-4e50-be5b-a467b95256da.png">

In this case I think it's safe to change `trigger_mode = "code"` because we actually still don't trigger in any case because of the other settings, but I think it would be better UX if buildkite errored in this case instead so you couldn't accidentally end up here.

**Comment by jradtilbrook** [comment]
Thanks for reporting this 👍 

We are approaching a v1.0 release and have done major refactors to the provider_settings part of the provider. I don't believe this is a relevant bug any more. If in fact this comes up again after the v1.0 release, please reopen it
