### ISSUE TITLE
Archive pipeline on destroy

### ISSUE THREAD

**Issue by christophermaier** [buildkite/terraform-provider-buildkite#195]
The [Github Terraform provider](https://registry.terraform.io/providers/integrations/github/latest/docs) has an [archive_on_destroy](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository#archive_on_destroy) argument for its [`github_repository` resource](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository), which allows you to optionally archive a Github repository when you remove the resource from your Terraform program, rather than completely deleting it.

Since Buildkite pipelines can also be archived, it would be convenient to add similar functionality to the Buildkite Terraform provider. This would be very useful for those that have auditing needs that require pipeline history, artifacts, etc. to be retained.

**Comment by jradtilbrook** [comment]
Ohh this is a really good idea @christophermaier! It probably ties into #177 as well but might need some changes. I'll have a further think/look into this

**Comment by mcncl** [comment]
Closing this issue as completed, support for this is addressed in https://github.com/buildkite/terraform-provider-buildkite/pull/296
