### ISSUE TITLE
$allow_rebuilds is not properly delcared

### ISSUE THREAD

**Issue by mhornbacher** [buildkite/terraform-provider-buildkite#203]
When using `cluster_id` PR #200 introduced `$allow_rebuilds` to the generated graphql. However this is not assigned in the values section of the graphql and as such always causes this error regardless of if `allow_rebuilds` is set in terraform:

```
│ Error: Variable $allow_rebuilds is declared by  but not used
```

**Comment by jradtilbrook** [comment]
hey @mhornbacher, #200 didn't add that argument, but should have fixed this error you're having. 

Can you confirm which version of the provider you are using and try out the latest release. 

(your error report is the same as #199 which should be fixed by #200

**Comment by mhornbacher** [comment]
Yes, I am using the latest release (0.11)

**Comment by jradtilbrook** [comment]
Thanks for checking @mhornbacher 👍 

The `allow_rebuilds` argument is present in both maps for create and update operations:

- https://github.com/buildkite/terraform-provider-buildkite/blob/main/buildkite/resource_pipeline.go#L327
- https://github.com/buildkite/terraform-provider-buildkite/blob/main/buildkite/resource_pipeline.go#L416

So I'm not sure how this is happening. Could you provide a minimum reproducible example to assist me in resolving this issue?

**Comment by mhornbacher** [comment]
Interesting, it seems to have resolved itself for us... I have attempted to isolate and reproduce again for a detailed restrospective but it no longer seems to replicate. Thanks for all your help!
