### ISSUE TITLE
[Feature request] add support for "Publish failed state early" in repository settings

### ISSUE THREAD

**Issue by puglyfe** [buildkite/terraform-provider-buildkite#211]
With the new "[Fail fast](https://buildkite.com/changelog/160-failing-builds-fast)" features, it would be great to be able to manage things like the "Publish failed state early" repository setting alongside things like [`publish_commit_status_per_step`](https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/pipeline#publish_commit_status_per_step).

**Comment by puglyfe** [comment]
I tried to check if this field is already exposed via API (which I presume would make this fairly straight forward), but the GraphQL explorer docs don't show input fields - https://buildkite.com/user/graphql/documentation/type/PipelineCreateInput.

**Comment by jradtilbrook** [comment]
Hey @puglyfe thanks for raising this request 👍 

As the changelog states, this was enabled for everyone in September last year. So there is nothing to do here
