### ISSUE TITLE
Adding data source for `buildkite_cluster`

### ISSUE THREAD

**Issue by lkerford** [buildkite/terraform-provider-buildkite#212]
We are trying to set the cluster on a pipeline which was generated through Terraform. We found a field `cluster_id` on the `buildkite_pipeline` resources (added in this [PR](https://github.com/buildkite/terraform-provider-buildkite/pull/181)). We were not able to find the matching data source for querying the ID of the cluster, similar to how there is a `buildkite_team` [data source](https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/data-sources/team). Would it make sense for that  to be added?

**Comment by jeremybumsted** [comment]
@lkerford Thank you for raising this issue. We'll take a look into this one and see what we can do 😄
