### ISSUE TITLE
removing cluster_id from a pipeline resource does not remove cluster from pipeline

### ISSUE THREAD

**Issue by albertywu** [buildkite/terraform-provider-buildkite#213]
After making this change to remove the cluster_id from a pipeline resource:

<img width="1210" alt="Screen Shot 2022-08-27 at 9 29 48 AM (1)" src="https://user-images.githubusercontent.com/1920766/187250160-6117d839-c45f-4748-995e-697e2b435086.png">

The cluster was not actually removed from the pipeline after running "terraform apply"

**Comment by albertywu** [comment]
I wonder if this issue is related to this one? https://github.com/buildkite/terraform-provider-buildkite/issues/212

cc: @jradtilbrook

**Comment by jradtilbrook** [comment]
#279 is now merged and we will release a new version next week. I'm going to close this out now ahead of that
