### ISSUE TITLE
`buildkite_pipeline` should manage settings on "Builds" page

### ISSUE THREAD

**Issue by jfirebaugh** [buildkite/terraform-provider-buildkite#226]
Settings on the `https://buildkite.com/<org>/<pipeline>/settings/builds` page should be managed by the `buildkite_pipeline` resource:

* [x] Build Skipping
* [x] Rebuilds
* [x] Timeouts
* [ ] Build Retention

**Comment by jradtilbrook** [comment]
Hey @jfirebaugh thanks for raising this. We are looking at implementing this and will update you soon.

**Comment by jradtilbrook** [comment]
Hey @jfirebaugh just giving an update that we have released support for configuring timeouts in [v0.12.2](https://github.com/buildkite/terraform-provider-buildkite/releases/tag/v0.12.2)

Build retention is in the work but a little more complex to implement. We'll let you know when it lands

**Comment by jradtilbrook** [comment]
I'm closing this off now as build retention is not going to be configurable
