### ISSUE TITLE
Check if the pipeline name is already taken

### ISSUE THREAD

**Issue by gu-kevin** [buildkite/terraform-provider-buildkite#255]
During the terraform planning step, provider should check if the newly created pipeline's name conflicts with an existing pipeline name. If it does, the plan should fail

**Comment by jradtilbrook** [comment]
I had never considered that! I like it 👍
We'll add this to our backlog but won't get to it for possibly a few weeks.

However, if you'd like to contribute a PR that would move things along much faster!

**Comment by lizrabuya** [comment]
Closing this at the moment as it is related to an open issue on the Terraform plugin pending: [Allow provider to define uniqueness of a resource #224](https://github.com/buildkite/terraform-provider-buildkite/issues/255#top).
