### ISSUE TITLE
Support managing clusters via a terraform resource

### ISSUE THREAD

**Issue by com6056** [buildkite/terraform-provider-buildkite#267]
It'd be great to support managing the new [clusters](https://buildkite.com/docs/agent/clusters) feature via terraform resources 🎉 Thanks!

**Comment by mcncl** [comment]
@com6056 thanks for the request! We're looking in to adding support for this, there are a couple of dependencies that'll need to be completed first, but we hope to get to this soon. I've penciled it in for _this month_, but that window may change depending on the resources we are able to allocate the dependencies for this.

**Comment by jradtilbrook** [comment]
Hey @com6056 just an update, we should have this ready to release by the end of this month 🤞

**Comment by mcncl** [comment]
@WBrettDavis we’ll take a look today. Most things should have been merged in to `main` for this to now be supported. 

Those of us who “own” the provider are Australia based, so we’ll look at this in a few hours and release this week if we can.

**Comment by jradtilbrook** [comment]
Hi @WBrettDavis we have merged in resources for cluster and cluster queue. We are still working on cluster agent tokens though. We are also working on a datasource for clusters. I don't think those will get merged this week but the following week and then we will cut a release with full support for clusters.

We are implementing support for import though so you could create the cluster and start using it and once we release, you can import it into state

**Comment by WBrettDavis** [comment]
@jradtilbrook and @mcncl Thanks for the update! We're currently using clusters in the way you described - creating them by hand, and then creating the agent queues in Terraform by filling in the cluster ID parameter manually. It'll be great once we can get all of this into Terraform though

**Comment by jradtilbrook** [comment]
@WBrettDavis I just realised that you won't be able to import cluster agent tokens. We don't show the token values after creation so it's impossible for terraform to import them with a token value, and without that, the resource is fairly useless. That will be the only resource you would have to recreate once we release cluster support. Clusters and cluster queues themselves support importing.

We are hoping to actually release this in a few hours as well 🙌

**Comment by jradtilbrook** [comment]
Alright its good to go! We've released https://github.com/buildkite/terraform-provider-buildkite/releases/tag/v0.20.0 with support for clusters
