### ISSUE TITLE
Error: input: Clusters has not been activated for your organization when modifying provider settings without clusters enabled

### ISSUE THREAD

**Issue by HugeIRL** [buildkite/terraform-provider-buildkite#287]
**Describe the bug**

Setup:
**Agent:** v3.47.0 (local)
**Provider:** v0.19.0

Using a basic setup of the provider and creating a pipeline resource, once the pipeline is created and you attempt to add the following provider settings:

```
provider_settings {
        publish_commit_status_per_step = true
}
```

You will get the error:

```
│ Error: input: Clusters has not been activated for your organization
│ 
│ 
│   with buildkite_pipeline.test-pipeline,
│   on test-pipeline.tf line 1, in resource "buildkite_pipeline" "test-pipeline":
│    1: resource "buildkite_pipeline" "test-pipeline" {
```

**To Reproduce**
1. Create a basic pipeline resource (mine just has buildkite-agent pipeline upload as the command) without **provider_settings publish_commit_status_per_step** being set.
2. Init, Plan and Apply using Terraform and check that the pipeline created successfully.
3. Go back to the resource and attempt to add:
```
provider_settings {
        publish_commit_status_per_step = true
}
```
4. You will get the error:
```
│ Error: input: Clusters has not been activated for your organization
│ 
│ 
│   with buildkite_pipeline.test-pipeline,
│   on test-pipeline.tf line 1, in resource "buildkite_pipeline" "test-pipeline":
│    1: resource "buildkite_pipeline" "test-pipeline" {
```

**Expected behavior**
No error as you are not passing a clusterID at this point in time. The apply should complete successfully.

**Additional context**
I also tested this by adding cluster_id = "" to see if it was a work around, to no success.

**Comment by jradtilbrook** [comment]
Oh no! Thanks for the bug report.

I think this might actually apply to any time you try update a pipeline, regardless of what you update.
#279 modified the UpdatePipeline function to use a new GraphQL library and it now sets `cluster_id` in the mutation no matter what. It should work because it sets it as null if not used but the API musn't be handling that properly. 

I'll look into it and get back with a path forward. For now, downgrading to <0.19.0 should fix this issue

**Comment by HugeIRL** [comment]
> Oh no! Thanks for the bug report.
> 
> I think this might actually apply to any time you try update a pipeline, regardless of what you update. #279 modified the UpdatePipeline function to use a new GraphQL library and it now sets `cluster_id` in the mutation no matter what. It should work because it sets it as null if not used but the API musn't be handling that properly.
> 
> I'll look into it and get back with a path forward. For now, downgrading to <0.19.0 should fix this issue

That's actually a great call out and something I didn't test when I was going through this. Thanks for checking on this.
