### ISSUE TITLE
Support for test analytics?

### ISSUE THREAD

**Issue by donallfg** [buildkite/terraform-provider-buildkite#299]
**Describe the bug**
Terraform provider doesn't support test analytics. 

**Expected behavior**

**Additional context**
We use the terraform provider for all our buildkite needs, and we've recently started looking into test analytics, but had to configure it through the UI online. We'd like to add management of our test analytics test suites to terraform.

**Comment by mcncl** [comment]
@donallfg 👋

Thanks for raising this issue. _Some_ Test Analytics functions have just been supported in our API, which means we're now in a position to support it in the Terraform provider too. We expect to get it done by the end of July 🙂

**Comment by donallfg** [comment]
By the end of july was a very accurate estimate. Thanks, we're looking forward to using it.
