### ISSUE TITLE
Support for Pipeline Templates

### ISSUE THREAD

**Issue by WBrettDavis** [buildkite/terraform-provider-buildkite#333]
Now that Pipeline Templates have been released for Enterprise accounts, it would be extremely helpful in our adoption of this new feature if we could manage these templates through Terraform.

**Comment by jradtilbrook** [comment]
Great suggestion thanks @WBrettDavis 👍

There is no API support for templates just yet but we'll see about getting an API and then into terraform

**Comment by jmandel1027** [comment]
This would be invaluable for our use case at Square. We have custom yaml tooling for translating yaml pipeline configs to Terraform.

If we can have template support via a tf resource. I know a lot of our teams would be appreciative.

**Comment by james2791** [comment]
Hey @jmandel1027 🙂 (also @WBrettDavis!)

Been working on the implementation of templates [here](https://github.com/buildkite/terraform-provider-buildkite/pull/429) with the API support for the respective queries/mutations - hope to get this through into `main`, and then subsequently available for the next release!

**Comment by jmandel1027** [comment]
Amazing!! Thanks gang! Looking forward to it

**Comment by james2791** [comment]
Hey @jmandel1027 - doing a loop over issues at present: as above with the work on that branch, all was moved through and  said resource is available from [v1.1.0](https://github.com/buildkite/terraform-provider-buildkite/releases/tag/v1.1.0) of the provider! (note the absolute latest is v1.1.1)

If you've got any more ideas/feature requests, please don't hesitate to whip them here  in GitHub as per this 🙂
