### ISSUE TITLE
Support for getting cluster agent token

### ISSUE THREAD

**Issue by WBrettDavis** [buildkite/terraform-provider-buildkite#335]
From what I can tell, there's no way to retrieve the token value as a data source for a cluster agent token resource. Having the ability to retrieve the token value would be needed to avoid hard-coding this in the TF config for cluster queues after the cluster has been created.

**Comment by jradtilbrook** [comment]
Thats correct. For security reasons, retrieving the token value from the API after creation is not supported. The token value is only accessible upon creation. This makes a datasource for cluster agent token quite not very useful so we haven't implemented it
