### ISSUE TITLE
Add support for setting cluster default queue

### ISSUE THREAD

**Issue by mbarrien** [buildkite/terraform-provider-buildkite#377]
I created a cluster and queue using Terraform, but found it did not support wait or block steps. It turns out no default queue is set when creating clusters and queues via Terraform. See https://forum.buildkite.community/t/buildkite-clusters-and-wait-block-step-unsupported/3210 for more info.

We need a way in Terraform to be able to set the default queue of a cluster. Ideally the buildkite_cluster resource would have a way to assign a default queue (e.g. set the default_queue_id field in the REST API).

I'd write a PR myself, but this is made tricky since a buildkite_cluster_queue needs a reference to the buildkite_cluster.id field, while a default queue field would need the buildkite_cluster_queue.id field, making for a circular dependency. You might be able to get away with a data resource, but no buildkite_cluster_queue resource exists currently.

Alternatively, a buildkite_cluster_default_queue resource could be added just for this.

**Comment by mcncl** [comment]
Hey @mbarrien! Thanks for submitting this! We'll take a look in to it and plan a solution to this issue.

**Comment by mcncl** [comment]
This is achievable with a seperate resource: https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/cluster_default_queue
