### ISSUE TITLE
Data could not be decoded from the state

### ISSUE THREAD

**Issue by reggiev** [buildkite/terraform-provider-buildkite#413]
**Describe the bug**
I am currently using 0.27.0 but attempting to migrate to 1.0.2
It seems like created stage from 0.27.0 is incompatible with 1.0.2

```
│ Error: Invalid resource instance data in state
│
│   on service-buildkite.tf line 1:
│    1: resource "buildkite_pipeline" "create_buildkite_repo" {
│
│ Instance buildkite_pipeline.create_buildkite_repo["serviceA"] data could not be decoded from the state: missing
│ expected {.
```
I have tried using `terraform init --reconfigure` but it did not work.

**Comment by jradtilbrook** [comment]
Hi @reggiev can you share the state for that pipeline and your terraform definition of it for us to debug?

**Comment by jradtilbrook** [comment]
I'm going to close this out for now. If you are able to provide more insight into this problem we can reopen it 👍
