### ISSUE TITLE
Value conversion error with buildkite_cluster_queue resource

### ISSUE THREAD

**Issue by yetanotheralex** [buildkite/terraform-provider-buildkite#417]
**Describe the bug**
Trying to create a buildkite cluster default queue with the new provider and terraform is outputting the following:
```
╷
│ Error: Value Conversion Error
│
│   with module.ci_cd.buildkite_cluster_queue.this["fasttrack"],
│   on ci-cd/cluster.tf line 8, in resource "buildkite_cluster_queue" "this":
│    8: resource "buildkite_cluster_queue" "this" {
│
│ An unexpected error was encountered trying to build a value. This is always an error in the provider. Please report the following to the provider developer:
│
│ Received null value, however the target type cannot handle null values. Use the corresponding `types` package type, a pointer type or a custom type that handles null values.
│
│ Path: description
│ Target Type: string
│ Suggested `types` Type: basetypes.StringValue
│ Suggested Pointer Type: *string
╵
```

**To Reproduce**
After playing with this, the steps necessary to reproduce are these:

Create a queue:
```
resource "buildkite_cluster" "this" {
  name        = "Primary cluster"
  description = "Primary cluster containing all agents and pipelines"
  emoji       = "🌊"
  color       = "#636076"
}

resource "buildkite_cluster_queue" "fasttrack" {
  cluster_id = buildkite_cluster.this.id
  key        = "fasttrack"
}
```

Go to the UI and set that queue as default manually, then re-apply the terraform. It will prompt you about modifying the resource, and will fail with the above error.

**Expected behavior**
No error.

**Comment by yetanotheralex** [comment]
Actually playing a bit more with this, it looks like the issue comes from the fact that the queue I'm trying to set as default with the provider was set as default manually prior to that, and that update-in-place is causing issues.

**Comment by yetanotheralex** [comment]
Played with the setting from the UI but cannot find a way to make the terraform code work, it always fails with the same error

**Comment by yetanotheralex** [comment]
Ok I've updated my initial issue and steps to reproduce, it had nothing to do with the default queue resource, and everything with the `default` setting from the UI

**Comment by jradtilbrook** [comment]
Thanks for this report @yetanotheralex 👍 

This looks even more general in that updating the resource is broken since a cluster queue description can be null. #418 should fix this up
