### ISSUE TITLE
Provider deleted pipeline despite `archive_pipeline_on_delete` being set to true

### ISSUE THREAD

**Issue by jeromefroe** [buildkite/terraform-provider-buildkite#421]
**Describe the bug**

The provider deleted a Buildkite pipeline instead of archiving it when the `archive_pipeline_on_delete` field was set to true in the configuration of the provider.

**Expected behavior**

The pipeline would be archived instead of deleted when the pipeline was removed from the Terraform configuration.

**Additional context**

We are using version 1.0.4 of the provider.

**Comment by jradtilbrook** [comment]
Oh no I'm sorry that happened. If you need the pipeline back, you can email support@buildkite.com and we can see about getting it back so you can archive it manually.

I'll aim to take a look at your related PR this week

**Comment by jeromefroe** [comment]
No worries! It wasn't an important pipeline for us so it's okay that it was deleted. Thanks for looking into the issue 🙇‍♂️
