### ISSUE TITLE
Support for Pipeline's color and emoji properties

### ISSUE THREAD

**Issue by gerardo** [buildkite/terraform-provider-buildkite#425]
Just like the [cluster resource](https://github.com/buildkite/terraform-provider-buildkite/blob/cec0095c986e8d74022e9ccee44d274cee99cbf0/docs/resources/cluster.md?plain=1#L24C1-L24C1) supports the `emoji` and `color` properties, graphql also provides those through the [pipeline](https://buildkite.com/docs/apis/graphql/schemas/object/pipeline) endpoint.

If would be nice to have those properties exposed through Terraform.

**Comment by jradtilbrook** [comment]
Oh yes we've overlooked that. Would you like to provide a PR to add those fields in @gerardo?

**Comment by james2791** [comment]
Hey @gerardo 👋

You may have noticed - but we've just recently merged [a PR including these attributes](https://github.com/buildkite/terraform-provider-buildkite/pull/427) to `main`, though its currently not released as of yet. The change will be introduced in the next provider version - shall loop once thats been released!

**Comment by gerardo** [comment]
Thanks for implementing this @james2791!
