### ISSUE TITLE
Add support for cluster token allowed IP addresses

### ISSUE THREAD

**Issue by nick-f** [buildkite/terraform-provider-buildkite#443]
It doesn't appear to be possible to set [cluster token allowed IP addresses](https://buildkite.com/docs/clusters/manage-clusters#set-up-clusters-restrict-access-for-a-cluster-token-by-ip-address) using the provider.

There's no mention of it in the [v1.1.1 documentation](https://registry.terraform.io/providers/buildkite/buildkite/1.1.1/docs/resources/cluster_agent_token).

Manually updating the IP restriction in the UI and doing a `terraform plan` says that there are:

```
No changes. Your infrastructure matches the configuration.
```

This would be super helpful to not need to make any GUI changes to the cluster config.

**Comment by james2791** [comment]
Thanks for raising this @nick-f!

Input for both the [create](https://buildkite.com/docs/apis/graphql/schemas/input-object/clusteragenttokencreateinput)/[update](https://buildkite.com/docs/apis/graphql/schemas/input-object/clusteragenttokenupdateinput) of Cluster agent tokens does have these available to use - we'll look at getting it added 🙂

**Comment by james2791** [comment]
Hey @nick-f!

As promised above - I've got a [PR](https://github.com/buildkite/terraform-provider-buildkite/pull/447) adding said attribute in. Once approved/merged, it'll be usable in the next release of the provider 🙂

**Comment by nick-f** [comment]
Amazing, love your work! I'll keep an eye out for the next release. Thanks James!

**Comment by james2791** [comment]
Hey @nick-f!

Thanks for your patience on the above - in the interim from my last comment, I've switched said attribute to a list vs just a string (makes it a little easier to maintain) and its now merged to [main](https://github.com/buildkite/terraform-provider-buildkite/pull/447).

Not promising specific version numbers (maybe `v1.2.0` (?) but it'll be inslusive in the next release!

**Comment by james2791** [comment]
@nick-f 👋 - just a complete full circle - `v1.2.0` [outed](https://github.com/buildkite/terraform-provider-buildkite/releases/tag/v1.2.0) not too long ago with the ability to set such allowed IPs to tokens - feel free to give it a go!

More fine-grained resource [docs](https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/cluster_agent_token#optional) on the registry for perusal also (which do live here also)!

**Comment by nick-f** [comment]
@james2791 That's great news, thank you! I'll give it a try and will report back if there's any issues ❤️
