### ISSUE TITLE
[Feature request] Support pipeline template assignment during pipeline resource creation

### ISSUE THREAD

**Issue by jasmineqin** [buildkite/terraform-provider-buildkite#470]
Currently, when we create the [pipeline resources](https://github.com/buildkite/terraform-provider-buildkite/blob/9d5c8d2f49217313c8b428a1678923f48696f4d1/docs/resources/pipeline.md) we couldn't assign a pipeline template to it upon creation. 

However, I think it will be a good feature add to support it when users want to streamline the pipeline creation process, and include steps such as assigning default pipeline template.

Something like `pipeline_template = xxx` in the below blob should suffice:
```
resource "buildkite_pipeline" "pipeline" {
  color      = "#000000"
  emoji      = ":buildkite:"
  name       = "repo"
  repository = "git@github.com:org/repo"

  provider_settings = {
    build_branches      = false
    build_tags          = true
    build_pull_requests = false
    trigger_mode        = "code"
  }

  pipeline_template = "org_default"  # or some other form of ID
  ...
}
```

Thank you.

**Comment by james2791** [comment]
Hello again @jasmineqin 👋

Just a full circle loop - `v1.4.0` has been [released](https://github.com/buildkite/terraform-provider-buildkite/releases/tag/v1.4.0) with the implementation of a pipeline template datasource/pipeline resource tweaks to add in the `pipeline_template_id` in place - feel free to give it a try!
