### ISSUE TITLE
registry.terraform.io documentation does not seem to match repo

### ISSUE THREAD

**Issue by grantwwu** [buildkite/terraform-provider-buildkite#476]
**Describe the bug**
At least one page on registry.terraform.io does not seem to match what's in the repo.

**To Reproduce**
1. Go to https://registry.terraform.io/providers/buildkite/buildkite/1.3.0/docs/resources/team
2. Observe the "A Cluster is a group of Agents that can be used to run your builds. Clusters are useful for grouping Agents by their capabilities, such as operating system, hardware, or location." text.
3. Go to https://github.com/buildkite/terraform-provider-buildkite/blob/v1.3.0/docs/resources/pipeline_team.md?plain=1
4. Observe that it does not contain said text.

**Expected behavior**
What's in this repo should probably match what's on the registry website.

**Comment by james2791** [comment]
Hey @grantwwu!

Good spot; this was an unintended carry over on the Team resource - was actually adjusted with [this](https://github.com/buildkite/terraform-provider-buildkite/pull/465) PR - once a newer version of the provider is released, the Terraform Registry page for it will be updated.
