### ISSUE TITLE
feature request: Add datasources to get the list of organization members

### ISSUE THREAD

**Issue by christophe-scalepad** [buildkite/terraform-provider-buildkite#527]
Hey,

Hope you are doing well.

## Description

As a company, we would like to manage RBAC in buildkite (and everywhere else) as IaC using terraform. We are currently missing the possibility to fetch the members of an organization. This would allow us to map our's idp's groups to teams we create  in buildkite. Currently with what is available to us, our only option would be to hardcode the user ids in our IaC which we would like to avoid.

This feature is already present in [another buildkite provider](https://registry.terraform.io/providers/tink-ab/buildkite/latest/docs/data-sources/org_members). This would allow us to fetch the user ids dynamically from buildkite using the data source and create a dynamic map with the users that we got from our idp's group.

I haven't looked in the other providers implementation, but I'm guessing it relies on your API's as well.

wishing you well

**Comment by mcncl** [comment]
Hey there @christophe-scalepad!

Thanks for raising this issue. Sounds like a useful thing we cold add in and shouldn't be too difficult to do; the queries are all available in the API as far as I can tell. We'll plan the work for this, but I can't see it being more that a few days to add in once it's picked up.


Cheers!

**Comment by ianchesal** [comment]
Here to +1 this -- this is the missing link between teams and organizing them in Terraform at present. Fetching the UUID for users to add them to teams currently O(hard) to do in any way that isn't incredible fragile.

**Comment by petetomasik** [comment]
Data sources for `organization_members` and `organization_member` have been implemented in https://github.com/buildkite/terraform-provider-buildkite/pull/590
