### ISSUE TITLE
Feature: add resource for generating a GraphQL token

### ISSUE THREAD

**Issue by lucasteligioridis** [buildkite/terraform-provider-buildkite#548]
# Description

Hi team! Would love to have a graph token generated in terraform like we do for the agent tokens, I can see how this might not be fully possibly though given the different scope that the graph token is under.

Would love to have these generated in code where we use them and automatically pass into our secrets management software. But I think for now a graph token needs to be associated to a user/bot where an agent token is associated to a queue.

Anyway just thought it was worth a conversation anyway! Thank you!

**Comment by mcncl** [comment]
Thanks @lucasteligioridis! 

I've relabelled it as an `enhancement` rather than a `bug` as I believe it needs engineering to add in. I don't think it's at all possible to create a user API token via the APIs; API access would be needed with likely all scopes in order to allow a token to have its scopes set, so you get a bit of a chicken/egg situation.

**Comment by lucasteligioridis** [comment]
@mcncl hey mate! Yeah I kind of thought this was a bit of a chicken/egg situation.

Perhaps in the future when Graph Tokens are able to have scopes set it would make some sense.
I'd like them in a similar sense to how agent tokens are generated etc...

**Comment by mcncl** [comment]
@lucasteligioridis yeah, that would be a nice to have. At the moment, tokens are scoped to a user who creates them, gives them the permissions they want it to have and then it _actually_ ends up with the permissions that the org allows via Teams etc (for REST) and everything for GraphQL.

I see this being something we could add in once organisational tokens are a thing and we no longer require things like machine users, or we change the way tokens are made. For now though, this isn’t something we’d be able to tackle given the function of tokens in Buildkite/how they’re created.

**Comment by lucasteligioridis** [comment]
Totally right and on that thought if it was a user token it's not ideal, agent tokens are kind of org level. So yeah when these are org level let's revisit as it will at least make sense then.

Thanks for checking in on this regardless 👍🏼
