### ISSUE TITLE
Support Auto-create webhook option in pipeline creation. 

### ISSUE THREAD

**Issue by ntascii** [buildkite/terraform-provider-buildkite#561]
**Is your feature request related to a problem? Please describe.**
Pipeline creation on Terraform doesn't support auto create webhook as an option like in the UI. This lack of parity prevents our smooth github integration for pipelines created using terraform. 

**Describe the solution you'd like**
Add an option/param to auto create webhook in terraform 

**Describe alternatives you've considered**
Make a separate API call after pipeline created using terraform. 

**Additional context**
Does it require the creation of a new resource/data source, is the function available in the API already?
No and the function should be in the API already but worth double checking. 

**Potential impact**
Cannot use IaC for BK in our CI platform.

**Comment by mcncl** [comment]
@ntascii thanks for raising this! If memory serves me correctly, this would require a second API call to the GitHub provider with the insertion of the webhook URL. Best practise really is that a provider should not adjust the state of another provider, in this instance, the Buildkite provider shouldn't really be allowed to adjust the state of the GitHub provider.

**Comment by mcncl** [comment]
I'd advise using the [github_repository_webhook](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_webhook) to set the webhook value after the creation of the pipeline 🙂
