### ISSUE TITLE
Submit GPG key to the OpenTofu registry

### ISSUE THREAD

**Issue by tthompson-figma** [buildkite/terraform-provider-buildkite#574]
**Is your feature request related to a problem? Please describe.**
We would like to migrate to OpenTofu with all providers' GPG signatures validated. However, OpenTofu skips validation for this provider because the OpenTofu registry does not have this provider's GPG key.

**Describe the solution you'd like**
You can follow this link to submit it: [Submit new Provider Signing Key](https://github.com/opentofu/registry/issues/new?assignees=&labels=provider-key%2Csubmission&projects=&template=provider_key.yml&title=Provider+Key%3A+)

If you don't have access to the public key anymore, it can be extracted from the terraform registry:

```bash
curl 'https://registry.terraform.io/v1/providers/buildkite/buildkite/1.12.0/download/linux/amd64' | jq --raw-output '.signing_keys | .gpg_public_keys | .[0] | .ascii_armor'
```

**Note:** For security reasons, it has to be submitted by the provider author for the OpenTofu registry to accept it.

**Describe alternatives you've considered**
Out-of-band GPG validation for providers missing keys in the OpenTofu registry. This is a pain :)

**Additional context**
OpenTofu is a fork of Terraform that is open-source, community-driven, and managed by the Linux Foundation.
Hashicorp https://github.com/opentofu/roadmap/issues/24#issuecomment-1699535216 for the terraform provider registry to disallow usage with things other than terraform, so OpenTofu had to build its own registry.

**Potential impact**
Allows OpenTofu users to use this provider with the same security guarantees they would using Terraform.

**Comment by tomowatt** [comment]
Hey @tthompson-figma 
Thanks for raising is up, we've now submiited the Provider Signing Key now: https://github.com/opentofu/registry/issues/1244

**Comment by tthompson-figma** [comment]
Thanks so much! 🙇
