### ISSUE TITLE
Can't clean up deleted state

### ISSUE THREAD

**Issue by mattdee123** [buildkite/terraform-provider-buildkite#582]
**Describe the bug**
I created a pipeline schedule through terraform, and then it was deleted manually, and I was unable to plan any more with the following error
```
Warning: Pipeline schedule not found

Removing Pipeline schedule from state...


Error: failed to read schema for buildkite_pipeline_schedule.image_publish_full in registry.terraform.io/hashicorp/buildkite: failed to instantiate provider "registry.terraform.io/hashicorp/buildkite" to obtain schema: unavailable provider "registry.terraform.io/hashicorp/buildkite"
```

**To Reproduce**
1. Create a schedule via terraform
2. Delete manually
3. Try to plan another terraform change

**Expected behavior**
I'd have expected it to remove the schedule from buildkite

**Additional context**
I'm particularly surprised to see registry.terraform.io/hashicorp/buildkite in the error message, given that it gives a 404

**Comment by tomowatt** [comment]
Hey @mattdee123 

Thanks for bringing this to our attention, are you able to share any more details on the versions of Terraform and the Provider you are using and if possible an excerpt on the Terraform configuration being used so we can check it out and replicate?

**Comment by tomowatt** [comment]
tried to replicate with Provider `v1.13.0` and Terraform `v1.9.8` and after manually deleting a Schedule, it is removed from State successfully before a new one is created.

```
Plan: 1 to add, 0 to change, 0 to destroy.
╷
│ Warning: Pipeline schedule not found
│
│   with buildkite_pipeline_schedule.test,
│   on main.tf line 35, in resource "buildkite_pipeline_schedule" "test":
│   35: resource "buildkite_pipeline_schedule" "test" {
│
│ Removing Pipeline schedule from state...
╵

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

buildkite_pipeline_schedule.test: Creating...
buildkite_pipeline_schedule.test: Creation complete after 0s [id=UGlwZWxpbmVTY2hlZHVsZS0tLTMzZjQ3OWYwLWQyNjgtNGIzMC1iNGVkLTk1NWIwNzRjZjQzZA==]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

But it is an interesting error message you received and not expected; but would be good to have more information for us to try and replicate and maybe see what might be the issue there.

**Comment by tomowatt** [comment]
@mattdee123 going to close this as not heard back from yourself of how you are experiencing this issue as it looks to be corrected in later versions of the Provider, but please re-open if you are still experiencing it and can share more details.
