### ISSUE TITLE
Environment variables aren't being picked up by the provider

### ISSUE THREAD

**Issue by nitrocode** [buildkite/terraform-provider-buildkite#64]
Thanks a lot for maintaining this @jradtilbrook. I played with it locally and it works well.

When I have the environment variables `BUILDKITE_API_TOKEN` and `BUILDKITE_ORGANIZATION` defined and set this in my `main.tf`

```hcl
provider "buildkite" {}
```

Then I run an apply, I get a prompt and a failure. The prompt shouldn't happen if it's reading the value from the environment variables.

```bash
✗ terraform apply
provider.buildkite.api_token
  API token with GraphQL access and `write_pipelines` scope

  Enter a value: aaaaaaaaaaaaaaaaaaaaaaaaa
buildkite_pipeline.repo1: Creating...

Error: non-200 OK status code: 401 Unauthorized body: "{\n  \"errors\": [\n    {\n      \"message\": \"Authentication required. Please supply a valid API Access Token: https://buildkite.com/docs/apis/graphql-api#authentication\"\n    }\n  ]\n}\n"
✗ 
```

I found that I had to set the following for the provider to work as expected.

```hcl
provider "buildkite" {
  api_token    = "...redacted..."
  organization = "...redacted..."
}
```

**Comment by jradtilbrook** [comment]
Hmm that is odd, I'll have to look into it. Perhaps its an issue from updating the terraform sdk since it's using that to resolve the configuration

**Comment by nitrocode** [comment]
Hi @jradtilbrook . Not sure what more I can give. I'm using the example hcl on the README, omitting the org and api token from the args, setting the environment variables either manually or using direnv, and running terraform commands. I see the prompt for a token and org even if the env vars are set...

**Comment by nitrocode** [comment]
> @nitrocode the set of commands or script would help I think

```
✗ terraform version
Terraform v0.14.6
+ provider registry.terraform.io/buildkite/buildkite v0.1.0

✗ cat providers.tf
provider "buildkite" {}

✗ echo $BUILDKITE_API_TOKEN
...snip...

✗ terraform plan
provider.buildkite.api_token
  API token with GraphQL access and `write_pipelines` scope

  Enter a value: no
```
