### ISSUE TITLE
Update terraform registry publishing after transferring repo to buildkite

### ISSUE THREAD

**Issue by jradtilbrook** [buildkite/terraform-provider-buildkite#70]
The GitHub action used to publish this provider to the registry has broken since moving to the Buildkite org. We need to set it up again by following the docs found at https://www.terraform.io/docs/registry/providers/publishing.html

Optionally move it to a Buildkite pipeline and integrate #67 into this as well

**Comment by yob** [comment]
I think I'll setup a Buildkite pipeline to push releases to GitHub, probably a distinct "deploy" (or release?) pipeline that's only visible to Buildkite staff.

**Comment by yob** [comment]
done! 0.0.17 is the first published release to use a Buildkite GPG key, and to go via a release pipeline on buildkite.com
