### ISSUE TITLE
Add source code provider_settings to a pipeline resource

### ISSUE THREAD

**Issue by vgrigoruk** [buildkite/terraform-provider-buildkite#85]
Currently, pipeline resource doesn't support configuring [provider_settings](https://buildkite.com/docs/apis/rest-api/pipelines#provider-settings-properties). REST API already supports this, so it would be nice to get them in Terraform.

**Comment by yob** [comment]
I agree, this would be a good addition.

We're on a skeleton staff over Christmas so I don't think we'll get to it over the next few weeks, but I'd happily review a PR if you can get one up :pray: 

Sadly I don't think the `PipelineCreate` graphql mutation supports `provider_settings`. However, there's prior art in this provider (eg #59 and [this](https://github.com/buildkite/terraform-provider-buildkite/blob/42b66042fb347879ddd4985c14ec9a70e9f63c59/buildkite/resource_pipeline.go#L287)) for falling back to REST calls for a feature until we can update the graphql mutation.

**Comment by vgrigoruk** [comment]
I'll try to learn golang basics over the holidays and hopefully will be able to make a PR :)

**Comment by vgrigoruk** [comment]
Implemented in #123
