### ISSUE TITLE
Add acceptance tests for each resource

### ISSUE THREAD

**Issue by jradtilbrook** [buildkite/terraform-provider-buildkite#9]
The current test is the bare minimum but barely covers anything useful so more should be added. We'd like to see acceptance tests for:

* [x] agent token #95
* [x] pipeline #99 
* [x] pipeline schedule #100 
* [x] team #103

**Comment by jradtilbrook** [comment]
Also add coverage badge to readme

**Comment by chloeruka** [comment]
We've now merged #95 #99 #100 and #103 which gets us much closer to complete resource coverage and closes this issue. 🎉
