### ISSUE TITLE
Data Provider For Pipeline

### ISSUE THREAD

**Issue by rfpludwick** [buildkite/terraform-provider-buildkite#93]
It would be pretty excellent for my team if there were a data provider for a pipeline. We have our GitHub repositories configured via Terraform, but we have those in a separate git repository from our Buildkite pipelines. So we have to manually copy the webhook URL from Buildkite into those Terraform configs.

Being able to use a data provider for a Buildkite pipeline means we can partially automate that in our other git repository.

**Comment by yob** [comment]
@rfpludwick This sounds like a great idea. We're pretty flat out at the moment, but we'd be happy to review a PR if you're up for it.

**Comment by rfpludwick** [comment]
@yob I'd love to take a shot at it... if I were up to it. My Go skills are nascent and I've never done anything for Terraform. If this is still a pending feature and I get my skills up to snuff, I'll give it a go.

**Comment by yob** [comment]
@rfpludwick - @chloeruka and I built up a bit of momentum on the provider codebase this week and I realised this would be less work to add than I thought.

I've opened a PR in #106, hopefully it survives the review gauntlet and can be included in the next release.
