### ISSUE TITLE
Feature request: add github settings to buildkite_pipeline

### ISSUE THREAD

**Issue by bluemalkin** [buildkite/terraform-provider-buildkite#98]
The github provider has the ability to add webhooks: https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_webhook

It would be great to have the ability to configure the guthub settings in the `buildkite_pipeline` resource so that we can automate everything in Terraform :-)

**Comment by yob** [comment]
Are you thinking we could have a `github_webhook` property on the `buildkite_pipeline`, suitable for passing to the `repository_webhook` resource in the github provider?

For Buildkite customers using the GitHub App style integration we also support creating the repository webhooks on your behalf, which can be triggered using the `PipelineCreateWebhookMutation` graphql mutation. One option we've considered is adding a `repository_webhook` resource to our provider, which uses that mutation.

**Comment by bluemalkin** [comment]
> Are you thinking we could have a `github_webhook` property on the `buildkite_pipeline`, suitable for passing to the `repository_webhook` resource in the github provider?
> 
> For Buildkite customers using the GitHub App style integration we also support creating the repository webhooks on your behalf, which can be triggered using the `PipelineCreateWebhookMutation` graphql mutation. One option we've considered is adding a `repository_webhook` resource to our provider, which uses that mutation.

Yes that sounds good !

**Comment by scream314** [comment]
Maybe I'm missing the point, but the pipeline has already a `webhook_url` output.

So you can just

```
resource "buildkite_pipeline" "this" {
[...]
}

resource "github_repository_webhook" "this" {
  repository = var.repository_name

  configuration {
    url          = buildkite_pipeline.this.webhook_url
    content_type = "application/json"
    insecure_ssl = false
    secret       = ""
  }

  events = var.webhook_events
}
```

**Comment by bluemalkin** [comment]
> github_repository_webhook

Your example just sets up a webhook on github. It has no effect on the configuration in `buildkite_pipeline`.

**Comment by yob** [comment]
@bluemalkin I'm a bit confused! 

> Are you thinking we could have a github_webhook property on the buildkite_pipeline, suitable for passing to the repository_webhook resource in the github provider?

It sounds like this isn't what you're after.

> For Buildkite customers using the GitHub App style integration we also support creating the repository webhooks on your behalf, which can be triggered using the PipelineCreateWebhookMutation graphql mutation. One option we've considered is adding a repository_webhook resource to our provider, which uses that mutation.

Is this what you're keen on?

> Your example just sets up a webhook on github. It has no effect on the configuration in buildkite_pipeline.

What effect on the pipeline are you looking for?

**Comment by bluemalkin** [comment]
https://registry.terraform.io/providers/buildkite/buildkite/latest/docs/resources/pipeline

Does not have a github attribute where I can set whether to build PRs etc...

Previously I used another BK provider which enabled me to.

**Comment by yob** [comment]
@bluemalkin oh! It sounds like this might be a dupe of issue #85. That's good news if so, because @vgrigoruk is working on addressing it in #123.

Let me know if I'm on the money, and maybe we can close this in favour of #85?

**Comment by bluemalkin** [comment]
@yob yes. Thanks
